name: 'Sample Git Workflow'
description: 'Check sample git workflow'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'shell'
  main: 'workflow-scripts/workflow.sh'
